/** MFDS Official Database (168 entries) */
window.MFDS_ADI_DATABASE = [
  {
    "no": 168,
    "name": "N-nitroso-mefloquine",
    "iupac": "(RS)-[2,8-bis(trifluoromethyl)quinolin-4-yl]-[(2R)-1-nitrosopiperidin-2-yl]methanol",
    "cas": null,
    "active": "메플로퀸염산염(Mefloquine)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 167,
    "name": "N-nitroso-hydroxyzine Impurity A",
    "iupac": "1-((4-Chlorophenyl)(phenyl)methyl)-4-nitrosopiperazine",
    "cas": "2005-04-1",
    "active": "히드록시진(Hydroxyzine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 166,
    "name": "N-nitroso-hydroxychloroquine EP Impurity C",
    "iupac": "N-(4-((7-Chloroquinolin-4-yl)amino)pentyl)-N-(2-hydroxyethyl)nitrous amide",
    "cas": null,
    "active": "히드록시클로로퀸(Hydroxychloroquine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 165,
    "name": "N-nitroso-propafenone impurity B",
    "iupac": "(R,E)-N-(3-(2-cinnamoylphenoxy)-2-hydroxypropyl)-N-propylnitrous amide",
    "cas": null,
    "active": "프로파페논(Propafenone)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 164,
    "name": "N-nitroso-desmethyl-ulipristal acetate (NDUPA)",
    "iupac": "[(8S,11R,13S,14S,17R)-17-acetyl-13-methyl-11-[4-[methyl(nitroso)amino]phenyl]-3-oxo-1,2,6,7,8,11,12,14,15,16-decahydrocyclopenta[a]phenanthren-17-yl] acetate",
    "cas": null,
    "active": "울리프리스탈아세테이트(Ulipristal Acetate)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 163,
    "name": "N-nitroso-venlafaxine EP Impurity H",
    "iupac": "N-(2-(1-Hydroxycyclohexyl)-2-(4-methoxyphenyl)ethyl)-N-(4-methoxyphenethyl)nitrous amide",
    "cas": null,
    "active": "벤라팍신(Venlafaxine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 162,
    "name": "N-nitroso-methylethanolamine (NMELA)",
    "iupac": "N-(2-hydroxyethyl)-N-methylnitrous amide",
    "cas": "26921-68-6",
    "active": "네포팜(Nefopam)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 161,
    "name": "N-nitroso-hydroxychloroquine EP Impurity D",
    "iupac": "N-(4-((7-Chloroquinolin-4-yl)amino)pentyl)-N-ethylnitrous amide",
    "cas": null,
    "active": "히드록시클로로퀸(Hydroxychloroquine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 160,
    "name": "N-nitroso-terbinafine degradant(NTD, NHMA)",
    "iupac": "N-[(2E)-6,6-dimethyl-2-hepten-4-yn-1-yl]-N-nitrosomethanamine",
    "cas": null,
    "active": "테르비나핀(Terbinafine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 159,
    "name": "N-nitroso-desmethyl-almotriptan",
    "iupac": "N-methyl-N-[2-[5-(pyrrolidin-1-ylsulfonylmethyl)-1H-indol-3-yl]ethyl]nitrous amide",
    "cas": null,
    "active": "알모트립탄(Almotriptan)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 158,
    "name": "N-nitroso-venlafaxine EP Impurity D",
    "iupac": "N-(2-benzoyl-4-chlorophenyl)-N-methylnitrous amide",
    "cas": "51145-18-7",
    "active": "벤라팍신(Venlafaxine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2026-08",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 157,
    "name": "N-nitroso-N-desmethyl roxithromycin",
    "iupac": "N-((2S,3R,4S,6R)-2-(((3R,4S,5S,6R,7R,9R,11S,12R,13S,14R,E)-14-ethyl-7,12,13-trihydroxy-4-(((2R,4R,5S,6S)-5-hydroxy-4-methoxy-4,6-dimethyltetrahydro-2H-pyran-2-yl)oxy)-10-(((2-methoxyethoxy)methoxy)imino)-3,5,7,9,11,13-hexamethyl-2-oxooxacyclotetradecan-6-yl)oxy)-3-hydroxy-6-methyltetrahydro-2H-pyran-4-yl)-N-methylnitrous amide",
    "cas": null,
    "active": "록시트로마이신(Roxithromycin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2026-06-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 156,
    "name": "N-nitroso-vonoprazan",
    "iupac": "N-[[5-(2-fluorophenyl)-1-pyridin-3-ylsulfonylpyrrol-3-yl]methyl]-N-methylnitrous amide",
    "cas": "2932441-73-9",
    "active": "보노프라잔(Vonoprazan)",
    "category": null,
    "ai": "96",
    "remark": "SAR/read-across, 참조물질 NDMA",
    "date": "2026-05-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 155,
    "name": "N-nitroso-carvedilol",
    "iupac": "N-(3-((9H-Carbazol-4-yl)oxy)-2-hydroxypropyl)-N-(2-(2-methoxyphenoxy)ethyl)nitrous amide",
    "cas": "2248746-67-8",
    "active": "카르베딜롤(Carvedilol)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 154,
    "name": "N-nitroso-olanzapine",
    "iupac": "2-methyl-4-(4-methylpiperazin-1-yl)-10-nitrosothieno[2,3-b][1,5]benzodiazepine",
    "cas": null,
    "active": "올란자핀(Olanzapine)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 153,
    "name": "N-nitroso-ephedrine",
    "iupac": "N-[(1S,2R)-1-hydroxy-1-phenylpropan-2-yl]-N-methylnitrous amide",
    "cas": "7181-48-8",
    "active": "에페드린(Ephedrine)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 152,
    "name": "N-nitroso-evocalcet",
    "iupac": "2-(4-((S)-3-(((R)-1-(naphthalen-1-yl)ethyl)(nitroso)amino)pyrrolidin-1-yl)phenyl)acetic acid",
    "cas": null,
    "active": "에보칼세트(Evocalcet)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 151,
    "name": "N-nitroso-vancomycin",
    "iupac": "(1S,2R,18R,19R,22S,25R,28R,40S)-48-[(2S,3R,4S,5S,6R)-3-[(2S,4S,5S,6S)-4-amino-5-hydroxy-4,6-dimethyloxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-22-(2-amino-2-oxoethyl)-5,15-dichloro-2,18,32,35,37-pentahydroxy-19-[[(2R)-4-methyl-2-[methyl(nitroso)amino]pentanoyl]amino]-20,23,26,42,44-pentaoxo-7,13-dioxa-21,24,27,41,43-pentazaoctacyclo[26.14.2.23,6.214,17.18,12.129,33.010,25.034,39]pentaconta-3,5,8(48),9,11,14,16,29(45),30,32,34(39),35,37,46,49-pentadecaene-40-carboxylic acid",
    "cas": "155386-25-7",
    "active": "반코마이신(Vancomycin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 150,
    "name": "N-nitroso-meglumine",
    "iupac": "N-methyl-N-(2,3,4,5,6-pentahydroxyhexyl)nitrous amide",
    "cas": "62137-31-9",
    "active": "메글루민(Meglumine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 149,
    "name": "N-nitroso-despropyl-ropinirole",
    "iupac": "N-(2-(2-oxoindolin-4-yl)ethyl)-N-propylnitrous amide",
    "cas": null,
    "active": "로피니롤(Ropinirole)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 148,
    "name": "N-nitroso-4-phenylpiperazine",
    "iupac": "1-nitroso-4-phenylpiperazine",
    "cas": "14340-33-1",
    "active": "레보드로프로피진(Levodropropizine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 147,
    "name": "N-nitroso-desmethyl-lercanidipine impurity C (EP)",
    "iupac": "3-(1-((3,3-diphenylpropyl)(nitroso)amino)-2-methylpropan-2-yl) 5-methyl 2,6-dimethyl-4-(3-nitrophenyl) pyridine-3,5-dicarboxylate",
    "cas": null,
    "active": "레르카니디핀(Lercanidipine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 146,
    "name": "N-nitroso-desmethyl-lercanidipine",
    "iupac": "3-(1-((3,3-diphenylpropyl)(nitroso)amino)-2-methylpropan-2-yl) 5-methyl 2,6-dimethyl-4-(3-nitrophenyl) -1,4-dihydropyridine-3,5-dicarboxylate",
    "cas": null,
    "active": "레르카니디핀(Lercanidipine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2026-03-24",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 145,
    "name": "N-nitroso-doravirine dimer",
    "iupac": "N,N-bis[[3-[[3-(3-chloro-5-cyanophenoxy)-2-oxo-4-(trifluoromethyl)-1-pyridinyl]methyl]-4-methyl-5-oxo-1,2,4-triazol-1-yl]methyl]nitrous amide",
    "cas": null,
    "active": "도라비린(Doravirine)",
    "category": null,
    "ai": "1500",
    "remark": "AMES 음성",
    "date": "2026-01-02",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 144,
    "name": "N-nitroso-posaconazole Impurity 1",
    "iupac": "1-(4-(((3R,5R)-5-((1H-1,2,4-triazol-1-yl)methyl)-5-(2,4-difluorophenyl)tetrahydrofuran-3-yl)methoxy)phenyl)-4-nitrosopiperazine",
    "cas": null,
    "active": "포사코나졸(Posaconazole)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 143,
    "name": "N-nitroso-trientine Impurity 1",
    "iupac": "N-(2-aminoethyl)-N-(2-((2-aminoethyl)amino)ethyl)nitrous amide",
    "cas": null,
    "active": "트리엔틴(Trientine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 142,
    "name": "N-nitroso-desmethyl-zolmitriptan",
    "iupac": "N-methyl-N-[2-[5-[[(4S)-2-oxo-1,3-oxazolidin-4-yl]methyl]-1H-indol-3-yl]ethyl]nitrous amide",
    "cas": null,
    "active": "졸미트립탄(Zolmitriptan)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 141,
    "name": "N-nitroso-articaine",
    "iupac": "Methyl 4-methyl-3-(2-(nitroso(propyl)amino)propanamido)thiophene-2-carboxylate",
    "cas": null,
    "active": "아티카인(Articaine)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 140,
    "name": "N-nitroso-acarbose",
    "iupac": "N-nitroso-4,6-dideoxy-4-[(1S,2S,3R,4S,5S)-3,4,5-trihydroxy-2-(hydroxymethyl)cyclohexyl]-α-D-glucopyranosyl-(1→4)-α-D-glucopyranosyl-(1→4)-α-D-glucopyranosyl-(1→4)-D-glucopyranose",
    "cas": null,
    "active": "아카보즈(Acarbose)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 139,
    "name": "N-nitroso-argatroban",
    "iupac": "(2R,4R)-4-methyl-1-(((3-methyl-1-nitroso-1,2,3,4-tetrahydroquinolin-8-yl)sulfonyl)-L-arginyl)piperidine-2-carboxylic acid",
    "cas": null,
    "active": "아가트로반(Argatroban)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 138,
    "name": "N-nitroso-piperazine (NPZ)",
    "iupac": "1-nitrosopiperazine",
    "cas": "5632-47-3",
    "active": "시프로플록사신(Ciprofloxacin)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 137,
    "name": "N-nitroso-vibegron",
    "iupac": "(S)-N-(4-(((2R,5S)-5-((R)-hydroxy(phenyl)methyl)-1-nitrosopyrrolidin-2-yl)methyl)phenyl)-4-oxo-4,6,7,8-tetrahydropyrrolo[1,2-a]pyrimidine-6-carboxamide",
    "cas": null,
    "active": "비베그론(Vibegron)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 136,
    "name": "4-(methylnitrosoamino)-1-(3-pyridinyl)-1-butanone (NNK)",
    "iupac": "N-methyl-N-(4-oxo-4-pyridin-3-ylbutyl)nitrous amide",
    "cas": "64091-91-4",
    "active": null,
    "category": null,
    "ai": "100",
    "remark": null,
    "date": "2025-08-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 135,
    "name": "N-nitroso-hydrochlorothiazide",
    "iupac": "6-chloro-4-nitroso-1,1-dioxo-2,3-dihydro-1λ6,2,4-benzothiadiazine-7-sulfonamide",
    "cas": null,
    "active": "히드로클로로티아지드(Hydrochlorothiazide)",
    "category": null,
    "ai": "33",
    "remark": "비변이원성 불순물, in vivo",
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 134,
    "name": "N-nitroso-fluoxetine",
    "iupac": "N-methyl-N-[3-phenyl-3-[4-(trifluoromethyl)phenoxy]propyl]nitrous amide",
    "cas": "150494-06-7",
    "active": "플루옥세틴(Fluoxetine)",
    "category": null,
    "ai": "100",
    "remark": "SAR/read-across, 참조물질 NNK",
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 133,
    "name": "N-nitroso-flecainide",
    "iupac": "N-((1-Nitrosopiperidin-2-yl)methyl)-2, 5-bis(2, 2, 2-trifluoroethoxy)benzamide",
    "cas": null,
    "active": "플레카이니드(Flecainide)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 132,
    "name": "N-nitroso-propranolol",
    "iupac": "N-(2-hydroxy-3-naphthalen-1-yloxypropyl)-N-propan-2-ylnitrous amide",
    "cas": "84418-35-9",
    "active": "프로프라놀롤(Propranolol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 131,
    "name": "N-nitroso-propafenone",
    "iupac": "N-(2-hydroxy-3-(2-(3-phenylpropanoyl)phenoxy)propyl)-N-propylnitrous amide",
    "cas": null,
    "active": "프로파페논(Propafenone)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 130,
    "name": "N-nitroso-frovatriptan",
    "iupac": "(6R)-6-[methyl(nitroso)amino]-6,7,8,9-tetrahydro-5H-carbazole-3-carboxamide",
    "cas": null,
    "active": "프로바트립탄(Frovatriptan)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 129,
    "name": "N-nitroso-pramipexole",
    "iupac": "N-(2-amino-4, 5, 6, 7-tetrahydrobenzo[d]thiazol-6-yl)-N-propylnitrous amide",
    "cas": null,
    "active": "프라미펙솔(Pramipexole)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 128,
    "name": "N-nitroso-furosemide",
    "iupac": "4-chloro-2-[furan-2-ylmethyl(nitroso)amino]-5-sulfamoylbenzoic acid",
    "cas": null,
    "active": "푸로세미드(Furosemide)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 127,
    "name": "N-nitroso-calcium folinate",
    "iupac": "N-[4-[[(2-amino-5-formyl-1,4,5,6,7,8-hexahydro-4-oxo-6-pteridinyl)methyl](nitroso)amino]benzoyl]-L-glutamic acid",
    "cas": null,
    "active": "폴리네이트칼슘(Calcium folinate/ Calcium levofolinate)",
    "category": null,
    "ai": "33",
    "remark": "비변이원성 불순물, in vivo",
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 126,
    "name": "N-nitroso-felodipine",
    "iupac": "5-O-ethyl 3-O-methyl 4-(2,3-dichlorophenyl)-2,6-dimethyl-1-nitroso-4H-pyridine-3,5-dicarboxylate",
    "cas": null,
    "active": "펠로디핀(Felodipine)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 125,
    "name": "N-nitroso-perindopril",
    "iupac": "(2S,3aS,7aS)-1-[(2S)-2-[[(2S)-1-ethoxy-1-oxopentan-2-yl]-nitrosoamino]propanoyl]-2,3,3a,4,5,6,7,7a-octahydroindole-2-carboxylic acid",
    "cas": null,
    "active": "페린도프릴(Perindopril)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 124,
    "name": "N-nitroso-phenylephrine",
    "iupac": "N-[(2R)-2-hydroxy-2-(3-hydroxyphenyl)ethyl]-N-methylnitrous amide",
    "cas": "78658-64-7",
    "active": "페닐레프린(Phenylephrine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 123,
    "name": "N-nitroso-paroxetine",
    "iupac": "(3S,4R)-3-(1,3-benzodioxol-5-yloxymethyl)-4-(4-fluorophenyl)-1-nitrosopiperidine",
    "cas": "2361294-43-9",
    "active": "파록세틴(Paroxetine)",
    "category": null,
    "ai": "1300",
    "remark": "SAR/read-across, 참조물질 NPIP",
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 122,
    "name": "N-nitroso-ticagrelor",
    "iupac": "N-((1R, 2S)-2-(3, 4-difluorophenyl)cyclopropyl)-N-(3-((1R, 2S, 3S, 4S)-2, 3-dihydroxy-4-(2-hydroxyethoxy)cyclopentyl)-5-(propylthio)-3H-[1, 2, 3]triazolo[4, 5-d]pyrimidin-7-yl)nitrous amide",
    "cas": "2476859-55-7",
    "active": "티카그렐러(Ticagrelor)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2024-01-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 121,
    "name": "N-nitroso-trimetazidine (NTMZ)",
    "iupac": "1-nitroso-4-[(2,3,4-trimethoxyphenyl)methyl]piperazine",
    "cas": "92432-50-3",
    "active": "트리메타지딘(Trimetazidine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 120,
    "name": "N-nitroso-N-desmethyl-trimebutine",
    "iupac": "2-(Methyl(nitroso)amino)-2-phenylbutyl 3, 4, 5-trimethoxybenzoate",
    "cas": null,
    "active": "트리메부틴(Trimebutine)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 119,
    "name": "N-nitroso-N-desmethyl-tramadol",
    "iupac": "N-[[(1R,2R)-2-hydroxy-2-(3-methoxyphenyl)cyclohexyl]methyl]-N-methylnitrous amide",
    "cas": null,
    "active": "트라마돌(Tramadol)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 118,
    "name": "N-nitroso-tetracaine",
    "iupac": "2-(dimethylamino)ethyl 4-(butyl(nitroso)amino)benzoate",
    "cas": null,
    "active": "테트라카인(Tetracaine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-01-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 117,
    "name": "N-nitroso-terbinafine impurity A",
    "iupac": "N-methyl-N-(napthalen-1-ylmethyl)nitrous amide",
    "cas": "296760-88-8",
    "active": "테르비나핀(Terbinafine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 116,
    "name": "N-nitroso-N-desmethyl-terbinafine",
    "iupac": "(E)-N-(6,6-Dimethylhept-2-en-4-yn-1-yl)-N-(naphthalen-1-ylmethyl)nitrous amide",
    "cas": null,
    "active": "테르비나핀(Terbinafine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 115,
    "name": "N-nitroso terazosin impurity N",
    "iupac": "(4-Nitrosopiperazin-1-yl) (tetrahydrofuran-2-yl)methanone",
    "cas": "2470438-57-2",
    "active": "테라조신(Terazosin)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 114,
    "name": "N-nitroso terazosin impurity C",
    "iupac": "6,7-dimethoxy-2-(4-nitrosopiperazin-1-yl)quinazolin-4-amine",
    "cas": null,
    "active": "테라조신(Terazosin)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 113,
    "name": "N-nitroso-tamsulosin",
    "iupac": "5-[(2R)-2-[2-(2-ethoxyphenoxy)ethyl-nitrosoamino]propyl]-2-methoxybenzenesulfonamide",
    "cas": "2892260-31-8",
    "active": "탐스로신(Tamsulosin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 112,
    "name": "N-nitroso-tigecycline",
    "iupac": "(4S, 4aS, 5aR, 12aS)-9-(2-(tert-butyl(nitroso)amino)acetamido)-4, 7-bis(dimethylamino)-3, 10, 12, 12a-tetrahydroxy-1, 11-dioxo-1, 4, 4a, 5, 5a, 6, 11, 12a-octahydrotetracene-2-carboxamide",
    "cas": null,
    "active": "타이가사이클린(Tigecycline)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 111,
    "name": "N-nitroso-desmethyl-tamoxifen",
    "iupac": "(Z)-N-(2-(4-(1, 2-diphenylbut-1-en-1-yl)phenoxy)ethyl)-N-methylnitrous amide",
    "cas": null,
    "active": "타목시펜(Tamoxifen)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 110,
    "name": "N-nitroso-clozapine",
    "iupac": "8-chloro-11-(4-methylpiperazin-1-yl)-5-nitroso-5H-dibenzo[b,e][1,4]diazepine",
    "cas": null,
    "active": "클로자핀(Cloazapine)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 109,
    "name": "N-nitroso-clozapine EP Impurity C",
    "iupac": "8-chloro-11-(4-nitrosopiperazin-1-yl)-5H-dibenzo[b, e][1, 4]diazepine",
    "cas": null,
    "active": "클로자핀(Clozapine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 108,
    "name": "N-nitroso-N-desmethyl clarithromycin",
    "iupac": "N-[(2S,3R,4S,6R)-2-[[(3R,4S,5S,6R,7R,9R,11R,12R,13S,14R)-14-ethyl-12,13-dihydroxy-4-[(2R,4R,5S,6S)-5-hydroxy-4-methoxy-4,6-dimethyloxan-2-yl]oxy-7-methoxy-3,5,7,9,11,13-hexamethyl-2,10-dioxo-oxacyclotetradec-6-yl]oxy]-3-hydroxy-6-methyloxan-4-yl]-N-methylnitrous amide",
    "cas": null,
    "active": "클래리트로마이신(Clarithromycin)",
    "category": null,
    "ai": "33",
    "remark": "비변이원성 불순물, SAR/read-across, 참조물질 N-nitroso-N-desmethyl-azithromycin",
    "date": "2026-07-01",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 107,
    "name": "N-nitroso-aryl piperazine / N-nitroso-desalkylquetiapine, NDAQ",
    "iupac": "11-(4-Nitrosopiperazin-1-yl)dibenzo[b,f][1,4]thiazepine",
    "cas": null,
    "active": "쿠에티아핀(Quetiapine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 106,
    "name": "N-nitroso Quetiapine HEEP Impurity",
    "iupac": "2-(2-(4-nitrosopiperazin-1-yl)ethoxy)ethan-1-ol",
    "cas": "73486-81-4",
    "active": "쿠에티아핀(Quetiapine)",
    "category": null,
    "ai": "1500",
    "remark": "AMES 음성",
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 105,
    "name": "N-nitroso-ketamine",
    "iupac": "N-[1-(2-chlorophenyl)-2-oxocyclohexyl]-N-methylnitrous amide",
    "cas": "86144-35-6",
    "active": "케타민(Ketamine)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 104,
    "name": "N-nitroso-caspofungin",
    "iupac": "(10R,12S)-N-((2R,9S,11R,12S,14aS,15S,20S,25aS)-20-((R)-3-amino-1-hydroxypropyl)-12-((2-aminoethyl)(nitroso)amino)-23-((1S,2S)-1,2-dihydroxy-2-(4-hydroxyphenyl)ethyl)-2,11,15-trihydroxy-6-((R)-1-hydroxyethyl)-5,8,14,19,22,25-hexaoxotetracosahydro-1H-dipyrrolo[2,1-c:2`,1`-l][1,4,7,10,13,16]hexaazacyclohenicosin-9-yl)-10,12-dimethyltetradecanamide",
    "cas": null,
    "active": "카스포펀진(Caspofungin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 103,
    "name": "Indapamide Impurity A",
    "iupac": "2-methyl-1-nitroso-2,3-dihydroindole",
    "cas": "85440-79-5",
    "active": "인다파미드(Indapamide)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 102,
    "name": "N-nitroso-iminodiacetic acid",
    "iupac": "2-[carboxymethyl(nitroso)amino] acetic acid",
    "cas": "25081-31-6",
    "active": "이소소르비드 모노니트레이트(Isosorbide mononitrate)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 101,
    "name": "N-nitroso-ethylenediamine-triacetic acid",
    "iupac": "2-[carboxymethyl-[2-[carboxymethyl(nitroso)amino] ethyl]amino]acetic acid",
    "cas": "862542-34-5",
    "active": "이소소르비드 모노니트레이트(Isosorbide mononitrate)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 100,
    "name": "N-nitroso-imatinib",
    "iupac": "N-(4-methyl-3-(nitroso(4-(pyridin-3-yl)pyrimidin-2-yl)amino)phenyl)-4-((4-methylpiperazin-1-yl)methyl)benzamide",
    "cas": null,
    "active": "이매티닙(Imatinib)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 99,
    "name": "N-nitroso-N-desmethylorphenadrine, NMOA",
    "iupac": "N-Methyl-N-(2-(phenyl(o-tolyl)methoxy)ethyl)nitrous Amide",
    "cas": null,
    "active": "오르페나드린(Orphenadrine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 98,
    "name": "N-nitroso-folic acid, NFA",
    "iupac": "2-[[4-[(2-amino-4-oxo-3H-pteridin-6-yl)methyl-nitrosoamino] benzoyl]amino]pentanedioic acid",
    "cas": "26360-21-4",
    "active": "엽산/폴산(Folic acid)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 97,
    "name": "N-nitroso-epinephrine",
    "iupac": "N-[(2R)-2-(3,4-dihydroxyphenyl)-2-hydroxyethyl]-N-methylnitrous amide",
    "cas": null,
    "active": "에피네프린(Epinephrine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 96,
    "name": "N-nitroso-esmolol",
    "iupac": "Methyl 3-(4-(2-hydroxy-3-(isopropyl(nitroso)amino)propoxy)phenyl)propanoate",
    "cas": null,
    "active": "에스몰롤(Esmolol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-01-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 95,
    "name": "N-nitroso-desmethyl-edoxaban",
    "iupac": "N-1-(5-chloropyridin-2-yl)-N2-((1S,2R,4S)-4-(dimethylcarbamoyl)-2-(5-nitroso-4,5,6,7-tetrahydrothiazolo[5,4-c]pyridine-2-carboxamido) cyclohexyl) oxalamide",
    "cas": null,
    "active": "에독사반(Edoxaban)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 94,
    "name": "N-nitroso-enalapril",
    "iupac": "(2S)-1-[(2S)-2-[[(2S)-1-ethoxy-1-oxo-4-phenylbutan-2-yl]-nitrosoamino]propanoyl]pyrrolidine-2-carboxylic acid",
    "cas": null,
    "active": "에날라프릴(Enalapril)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 93,
    "name": "N-nitroso-ambroxol",
    "iupac": "N-[(2-amino-3,5-dibromophenyl)methyl]-N-[4-hydroxycyclohexyl]nitrous amide",
    "cas": null,
    "active": "암브록솔(Ambroxol)",
    "category": null,
    "ai": "1500",
    "remark": "AMES 음성",
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 92,
    "name": "3-amino-N-nitrosopiperidine",
    "iupac": "1-nitrosopiperidin-3-amine",
    "cas": "2819242-71-0",
    "active": "알로글립틴(Alogliptin)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-01-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 91,
    "name": "N-nitroso-apixaban impurity B",
    "iupac": "5-[4-[3-carbamoyl-1-(4-methoxyphenyl)-7-oxo-4,5-dihydropyrazolo[3,4-c]pyridin-6-yl]-N-nitrosoanilino]pentanoic acid",
    "cas": null,
    "active": "아픽사반(Apixaban)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 90,
    "name": "N-nitroso-atomoxetine",
    "iupac": "N-methyl-N-[(3R)-3-(2-methylphenoxy)-3-phenylpropyl]nitrous amide",
    "cas": null,
    "active": "아토목세틴(Atomoxetine)",
    "category": null,
    "ai": "100",
    "remark": "SAR/read-across, 참조물질 NNK",
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 89,
    "name": "N-nitroso-atenolol",
    "iupac": "2-[4-[2-hydroxy-3-[nitroso(propan-2-yl)amino]propoxy]phenyl]acetamide",
    "cas": "134720-04-0",
    "active": "아테놀롤(Atenolol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 88,
    "name": "N-nitroso-N-desmethyl-azithromycin",
    "iupac": "(2R,3S,4R,5R,8R,10R,11R,12S,13S,14R)-2-ethyl-3,4,10-trihydroxy-13-[(2R,4R,5S,6S)-5-hydroxy-4-methoxy-4,6-dimethyloxan-2-yl]oxy-11-[(2S,3R,4S,6R)-3-hydroxy-6-methyl-4-(methylamino)oxan-2-yl]oxy-3,5,6,8,10,12,14-heptamethyl-1-oxa-6-azacyclopentadecan-15-one",
    "cas": null,
    "active": "아지스로마이신(Azithromycin)",
    "category": null,
    "ai": "33",
    "remark": "비변이원성 불순물, in vivo",
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 87,
    "name": "N-nitroso-azaerythromycin",
    "iupac": "(2R, 3S, 4R, 5R, 8R, 10R, 11R, 12S, 13S, 14R)-11-(((2S, 3R, 4S, 6R)-4-(dimethylamino)-3-hydroxy-6-methyltetrahydro-2H-pyran-2-yl)oxy)-2-ethyl-3, 4, 10-trihydroxy-13-(((2R, 4R, 5S, 6S)-5-hydroxy-4-methoxy-4, 6-dimethyltetrahydro-2H-pyran-2-yl)oxy)-3, 5, 8, 10, 12, 14-hexamethyl-6-nitroso-1-oxa-6-azacyclopentadecan-15-one",
    "cas": null,
    "active": "아지스로마이신(Azithromycin)",
    "category": null,
    "ai": "33",
    "remark": "비변이원성 불순물, in vivo",
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 86,
    "name": "N-nitroso-desmethyl-azelastine",
    "iupac": "4-(4-Chlorobenzyl)-2-(1-nitrosoazepan-4-yl)phthalazin-1(2H)-one",
    "cas": null,
    "active": "아젤라스틴(Azelastine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 85,
    "name": "1-(2,3-dichlorophenyl)-4-nitrosopiperazine",
    "iupac": "1-(2,3-dichlorophenyl)-4-nitrosopiperazine",
    "cas": "2221987-86-4",
    "active": "아리피프라졸(Aripiprazole)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 84,
    "name": "N-nitroso-silodosin",
    "iupac": "1-(3-hydroxypropyl)-5-[(2R)-2-[nitroso-[2-[2-(2,2,2-trifluoroethoxy)phenoxy]ethyl]amino]propyl]-2,3-dihydroindole-7-carboxamide",
    "cas": null,
    "active": "실로도신(Silodosin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 83,
    "name": "N-nitroso-cilazapril",
    "iupac": "(1S, 9S)-9-[[(1S)-1-(Ethoxycarbonyl)-3-phenylpropyl]nitrosoamino]octahydro-10-oxo-6H-pyridazino[1, 2-a][1, 2]diazepine-1-carboxylic Acid",
    "cas": "1053740-92-3",
    "active": "실라자프릴(Cilazapril)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 82,
    "name": "N-nitroso-N-desmethyl-sildenafil",
    "iupac": "5-(2-ethoxy-5-((4-nitrosopiperazin-1-yl)sulfonyl)phenyl)-1-methyl-3-propyl-1H-pyrazolo[4, 3-d]pyrimidin-7(6H)-one",
    "cas": null,
    "active": "실데나필(Sildenafil)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 81,
    "name": "1-diphenylmethyl-4-nitrosopiperazine",
    "iupac": "1-benzhydryl-4-nitrosopiperazine",
    "cas": "1698-25-5",
    "active": "신나리진(cinnarizine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-01-09",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 80,
    "name": "N-nitroso-ciprofloxacin",
    "iupac": "1-cyclopropyl-6-fluoro-7-(4-nitrosopiperazin-1-yl)-4-oxoquinoline-3-carboxylic acid",
    "cas": "864443-44-7",
    "active": "시프로플록사신(Ciprofloxacin)",
    "category": null,
    "ai": "33",
    "remark": "비변이원성 불순물, in vivo",
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 79,
    "name": "N-nitroso-N-desmethyl-citalopram",
    "iupac": "N-(3-(5-cyano-1-(4-fluorophenyl)-1, 3-dihydroisobenzofuran-1-yl)propyl)-N-methylnitrous amide",
    "cas": null,
    "active": "시탈로프람(Citalopram)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 78,
    "name": "7-nitroso-3-(trifluoromethyl)-5,6,7,8-tetrahydro[1,2,4]triazolo-[4,3-a]pyrazine (NTTP)",
    "iupac": "7-nitroso-3-(trifluoromethyl)-6,8-dihydro-5H-[1,2,4]triazolo[4,3-a]pyrazine",
    "cas": "2892260-32-9",
    "active": "시타글립틴(Sitagliptin)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2024-10-25",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 77,
    "name": "2,2,5-trimethyl-3-nitroso-1,3-oxazolidine",
    "iupac": "2,2,5-trimethyl-3-nitroso-1,3-oxazolidine",
    "cas": "77400-46-5",
    "active": "시아노코발라민(Cyanocobalamine)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 76,
    "name": "N-nitroso-cinacalcet",
    "iupac": "(R)-N-(1-(naphthalen-1-yl)ethyl)-N-(3-(3-(trifluoromethyl)phenyl)propyl)nitrous amide",
    "cas": null,
    "active": "시나칼세트(Cinacalcet)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-01-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 75,
    "name": "N-nitroso-pseudoephedrine",
    "iupac": "N-((1S,2S)-1-Hydroxy-1-phenylpropan-2-yl)-N-methylnitrous amide",
    "cas": "1850-88-0",
    "active": "슈도에페드린(Pseudoephedrine)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 74,
    "name": "N-nitroso-N-desmethyl-sumatriptan",
    "iupac": "N-methyl-1-(3-(2-(methyl(nitroso)amino)ethyl)-1H-indol-5-yl)methanesulfonamide",
    "cas": null,
    "active": "수마프립탄(Sumatriptan)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 73,
    "name": "N-nitroso-sotalol",
    "iupac": "N-[4-[1-hydroxy-2-[nitroso(propan-2-yl)amino]ethyl]phenyl]methanesulfonamide",
    "cas": "134720-07-3",
    "active": "소타롤(Sotalol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 72,
    "name": "N-nitroso-celiprolol",
    "iupac": "3-(3-Acetyl-4-(3-(tert-butyl(nitroso)amino)-2-hydroxypropoxy)phenyl)-1,1-diethylurea",
    "cas": null,
    "active": "셀리프롤롤(Celiprolol)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 71,
    "name": "N-nitroso-sertraline",
    "iupac": "N-(4-(3, 4-dichlorophenyl)-1, 2, 3, 4-tetrahydronaphthalen-1-yl)-N-methylnitrous amide",
    "cas": null,
    "active": "설트랄린(Sertraline)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 70,
    "name": "N-nitroso-salbutamol",
    "iupac": "N-tert-butyl-N-[2-hydroxy-2-[4-hydroxy-3-(hydroxymethyl)phenyl]ethyl]nitrous amide",
    "cas": null,
    "active": "살부타몰(Salbutamol)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 69,
    "name": "N-nitroso-vildagliptin",
    "iupac": "N-(2-((S)-2-cyanopyrrolidin-1-yl)-2-oxoethyl)-N-((1r,3R,5R,7S)-3-hydroxyadamantan-1-yl)nitrous amide",
    "cas": null,
    "active": "빌다글립틴(Vildagliptin)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 68,
    "name": "N-nitroso vildagliptin amide impurity",
    "iupac": "(S)-1-(2-(((1r, 3R, 5R, 7S)-3-hydroxyadamantan-1-yl)(nitroso)amino)acetyl)pyrrolidine-2-carboxamide(S)-1-(2-(((1r, 3R, 5R, 7S)-3-hydroxyadamantan-1-yl)(nitroso)amino)acetyl)pyrrolidine-2-carboxamide",
    "cas": null,
    "active": "빌다글립틴(Vildagliptin)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 67,
    "name": "N-nitroso-bisoprolol (NBP)",
    "iupac": "N-[2-hydroxy-3-[4-(2-propan-2-yloxyethoxymethyl)phenoxy]propyl]-N-propan-2-ylnitrous amide",
    "cas": "2820170-76-9",
    "active": "비소프롤롤(Bisoprolol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 66,
    "name": "N-nitroso-bupropion",
    "iupac": "N-tert-butyl-N-[1-(3-chlorophenyl)-1-oxopropan-2-yl]nitrous amide",
    "cas": "2763780-10-3",
    "active": "부프로피온(Bupropion)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 65,
    "name": "N-nitroso-buspirone Impurity 1",
    "iupac": "2-(4-nitrosopiperazine-1-yl)-pyrimidine",
    "cas": "872826-80-7",
    "active": "부스피론(Buspirone)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 64,
    "name": "N-nitroso-vortioxetine",
    "iupac": "1-[2-(2,4-dimethylphenyl)sulfanylphenyl]-4-nitrosopiperazine",
    "cas": null,
    "active": "보티옥세틴(Vortioxetine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 63,
    "name": "3-(dimethylamino)propyl 2-[benzyl(nitroso)amino]benzoate",
    "iupac": "3-(dimethylamino)propyl 2-[benzyl(nitroso)amino]benzoate",
    "cas": "87453-76-7",
    "active": "벤지다민(Benzydamine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 62,
    "name": "N-nitroso-betaxolol",
    "iupac": "N-(3-(4-(2-(cyclopropylmethoxy)ethyl)phenoxy)-2-hydroxypropyl)-N-isopropylnitrous amide",
    "cas": null,
    "active": "베탁솔롤(Betaxolol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 61,
    "name": "N-nitroso-betahistine",
    "iupac": "N-methyl-N-(2-pyridin-2-ylethyl)nitrous amide",
    "cas": "32635-81-7",
    "active": "베타히스틴(Betahisitne)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 60,
    "name": "N-nitroso-valsartan cyano-desvalerylmethylester",
    "iupac": "(S)-Methyl 2-(((2'-cyano-[1,1'-biphenyl]-4-yl)methyl)(nitroso)amino)-3-methylbutanoate",
    "cas": null,
    "active": "발사르탄(Valsartan)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 59,
    "name": "N-nitroso-N-methyl-valacyclovir",
    "iupac": "2-[(2-amino-6-oxo-1H-purin-9-yl)methoxy]ethyl 3-methyl-2-[methyl(nitroso)amino]butanoate",
    "cas": null,
    "active": "발라시클로비르(Valacyclovir)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 58,
    "name": "N-nitroso-N-ethyl-valacyclovir",
    "iupac": "2-[(2-amino-6-oxo-1H-purin-9-yl)methoxy]ethyl 2-[ethyl(nitroso)amino]-3-methylbutanoate",
    "cas": null,
    "active": "발라시클로비르(Valacyclovir)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 57,
    "name": "N-nitroso-varenicline, NNV",
    "iupac": "(1R,12S)-14-nitroso-5,8,14-triazatetracyclo[10.3.1.02,11.04,9]hexadeca-2,4,6,8,10-pentaene",
    "cas": "2755871-02-2",
    "active": "바레니클린(Varenicline)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-06-21",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 56,
    "name": "N-nitroso-N-desmethyl-mirtazepine",
    "iupac": "2-nitroso-1, 2, 3, 4, 10, 14b-hexahydrobenzo[c]pyrazino[1, 2-a]pyrido[3, 2-f]azepine",
    "cas": null,
    "active": "미르타자핀(Mirtazapine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 55,
    "name": "N-nitroso-mirabegron",
    "iupac": "(R)-2-(2-Aminothiazol-4-yl)-N-(4-(2-((2-hydroxy-2-phenylethyl)(nitroso)amino)ethyl)phenyl)acetamide",
    "cas": null,
    "active": "미라베그론(Mirabegron)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 54,
    "name": "N-(4-aminophenethyl)-N-(2-hydroxy-2-phenylethyl)nitrous amide",
    "iupac": "(R)-N-(4-aminophenethyl)-N-(2-hydroxy-2-phenylethyl)nitrous amide",
    "cas": null,
    "active": "미라베그론(Mirabegron)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 53,
    "name": "N-(2-hydroxy-2-phenylethyl)-N-(4-nitrophenethyl)nitrous amide",
    "iupac": "(R)-N-(2-hydroxy-2-phenylethyl)-N-(4-nitrophenethyl)nitrous amide",
    "cas": null,
    "active": "미라베그론(Mirabegron)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 52,
    "name": "N-nitroso-moxifloxacin",
    "iupac": "1-cyclopropyl-6-fluoro-8-methoxy-7-((4aS,7aS)-1-nitrosooctahydro-6H-pyrrolo[3,4-b]pyridin-6-yl)-4-oxo-1,4-dihydroquinoline-3-carboxylic acid",
    "cas": null,
    "active": "목시플록사신(Moxifloxacin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 51,
    "name": "1-nitroso-pyrrolopiperidine",
    "iupac": "(4aS,7aS)-1-Nitrosooctahydro-1H-pyrrolo[3,4-b]pyridine",
    "cas": null,
    "active": "목시플록사신(Moxifloxacin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 50,
    "name": "N-nitroso-methylphenidate (NMPH)",
    "iupac": "methyl 2-(1-nitrosopiperidin-2-yl)-2-phenylacetate",
    "cas": "55557-03-4",
    "active": "메틸페니데이트(Methylphenidate)",
    "category": null,
    "ai": "1300",
    "remark": "SAR/read-across, 참조물질 NPIP",
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 49,
    "name": "N-nitroso-ritalinic acid",
    "iupac": "2-(1-nitrosopiperidin-2-yl)-2-phenylacetic acid",
    "cas": null,
    "active": "메틸페니데이트(Methylphenidate)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 48,
    "name": "N-nitroso-metoprolol",
    "iupac": "N-[2-hydroxy-3-[4-(2-methoxyethyl)phenoxy]propyl]-N-propan-2-ylnitrous amide",
    "cas": "134720-05-1",
    "active": "메토프롤롤(Metoprolol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 47,
    "name": "N-nitroso-meropenem",
    "iupac": "(4R, 5S, 6S)-3-(((3S, 5S)-5-(dimethylcarbamoyl)-1-nitrosopyrrolidin-3-yl)thio)-6-((R)-1-hydroxyethyl)-4-methyl-7-oxo-1-azabicyclo[3.2.0]hept-2-ene-2-carboxylic acid",
    "cas": null,
    "active": "메로페넴(Meropenem)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 46,
    "name": "N-nitroso-2,4-thiazole amine (NNTA)",
    "iupac": "N-((2-isopropylthiazol-4-yl)methyl)-N-methylnitrous amide",
    "cas": null,
    "active": "리토나비르(Ritonavir), 코비시스타트(Cobicistat)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 45,
    "name": "N-nitroso-desformyl-riociguat",
    "iupac": "N-(4,6-diamino-2-(1-(2-fluorobenzyl)-1H-pyrazolo[3,4-b]pyridin-3-yl)pyrimidin-5-yl)-N-methylnitrous",
    "cas": null,
    "active": "리오시구앗(Riociguat)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 44,
    "name": "N-nitroso-lisinopril",
    "iupac": "N2-((S)-1-carboxy-3-phenylpropyl)-N2-nitroso-L-lysyl-L-proline",
    "cas": null,
    "active": "리시노프릴(Linsinopril)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 43,
    "name": "N-nitroso-ribociclib impurity 1",
    "iupac": "7-cyclopentyl-N,N-dimethyl-2-((5-(4-nitrosopiperazin-1-yl)pyridine-2-yl)amino)-7H-pyrrolo[2,3-d]pyrimidine-6-carboxamide",
    "cas": null,
    "active": "리보시클립(Ribociclib)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 42,
    "name": "N-nitroso-N-desmethyl rivastigmine",
    "iupac": "[3-[(1S)-1-[methyl(nitroso)amino] ethyl]phenyl] N-ethyl-N-methyl carbamate",
    "cas": null,
    "active": "리바스티그민(Rivastigmine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 41,
    "name": "Rivaroxaban nitroso Impurity 5",
    "iupac": "N-(3-Chloro-2-hydroxypropyl)-N-(4-(3-oxomorpholino)phenyl)nitrous amide",
    "cas": null,
    "active": "리바록사반(Rivaroxaban)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 40,
    "name": "Rivaroxaban nitroso Impurity 2",
    "iupac": "N-(3-(1,3-dioxoisoindolin-2-yl)-2-hydroxypropyl)-N-(4-(3-oxomorpholino) phenyl)nitrous amide",
    "cas": null,
    "active": "리바록사반(Rivaroxaban)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 39,
    "name": "Rivaroxaban nitroso Impurity 1",
    "iupac": "N-(2-hydroxyethyl)-N-phenyl-nitrous amide",
    "cas": "25413-76-7",
    "active": "리바록사반(Rivaroxaban)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 38,
    "name": "N-Nitroso-rivaroxaban open-ring acid",
    "iupac": "(S)-2-(2-((4-(5-((5-chlorothiophene-2-carboxamido)methyl)-2-oxooxazolidin-3-yl)phenyl)(nitroso)amino)ethoxy) acetic acid",
    "cas": null,
    "active": "리바록사반(Rivaroxaban)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 37,
    "name": "N-Nitroso-rivaroxaban amide",
    "iupac": "(S)-5-chloro-N-(2-hydroxy-3-(nitroso (4-(3-oxomorpholino)phenyl)amino) propyl)thiophene-2-carboxamide",
    "cas": null,
    "active": "리바록사반(Rivaroxaban)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 36,
    "name": "N-nitroso-desethyllidocaine",
    "iupac": "N-(2,6-dimethylphenyl)-2-[ethyl(nitroso)amino]acetamide",
    "cas": null,
    "active": "리도카인(Lidocaine)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 35,
    "name": "N-nitroso-folinic acid",
    "iupac": "N-[4-[[(2-amino-5-formyl-1,4,5,6,7,8-hexahydro-4-oxo-6-pteridinyl)methyl](nitroso)amino]benzoyl]-L-glutamic acid",
    "cas": null,
    "active": "류코보린(Leucovorin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 34,
    "name": "N-nitroso-2,6-pipecoloxilidide",
    "iupac": "N-(2,6-dimethylphenyl)-1-nitrosopiperidine-2-carboxamide",
    "cas": null,
    "active": "로피바카인(Ropivacaine)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 33,
    "name": "N-nitroso-N-desmethyl-levofloxacin",
    "iupac": "(2S)-7-fluoro-2-methyl-6-(4-nitrosopiperazin-1-yl)-10-oxo-4-oxa-1-azatricyclo[7.3.1.05,13]trideca-5(13),6,8,11-tetraene-11-carboxylic acid",
    "cas": "1152314-62-9",
    "active": "레보플록사신(Levofloxacin)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 32,
    "name": "N-nitroso-rasagiline",
    "iupac": "N-[(1R)-2,3-dihydro-1H-inden-1-yl]-N-prop-2-ynylnitrous amide",
    "cas": "2470278-90-9",
    "active": "라사길린(Rasagiline)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 31,
    "name": "N-nitroso-labetalol",
    "iupac": "2-hydroxy-5-[1-hydroxy-2-[nitroso(4-phenylbutan-2-yl)amino]ethyl]benzamide",
    "cas": "2820170-74-7",
    "active": "라베타롤(Labetalol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 30,
    "name": "N-nitroso-ramipril",
    "iupac": "(2S,3aS,6aS)-1-(N-((S)-1-ethoxy-1-oxo-4-phenylbutan-2-yl)-N-nitroso-L-alanyl)octahydrocyclopenta[b]pyrrole-2-carboxylic acid",
    "cas": null,
    "active": "라미프릴(Ramipril)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 29,
    "name": "N-nitroso-ranolazine impurity 1",
    "iupac": "1-(2-methoxyphenoxy)-3-(4-nitrosopiperazin-1-yl)propan-2-ol",
    "cas": null,
    "active": "라놀라진(Ranolazine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 28,
    "name": "N-nitroso-diclofenac",
    "iupac": "2-[2-(2,6-dichloro-N-nitrosoanilino)phenyl]acetic acid",
    "cas": "66505-80-4",
    "active": "디클로페낙(Diclofenac)",
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 27,
    "name": "N-nitroso-N-desmethyl-diphenhydramine",
    "iupac": "N-(2-benzhydryloxyethyl)-N-methylnitrous amide",
    "cas": "55855-43-1",
    "active": "디멘히드리네이트(Dimenhydrinate), 디펜히드라민(Diphenhydramine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2025-01-09",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 26,
    "name": "N-nitroso-duloxetine",
    "iupac": "(S)-N-methyl-N-(3-(naphthalen-1-yloxy)-3-(thiophen-2-yl)propyl)nitrous amide",
    "cas": null,
    "active": "둘록세틴(Duloxetine)",
    "category": null,
    "ai": "100",
    "remark": "SAR/read-across, 참조물질 NNK",
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 25,
    "name": "N-nitroso-N-methyl-2-[1-phenyl-1-(2-pyridinyl)methoxy]ethanamine",
    "iupac": "N-methyl-N-(2-(phenyl(pyridin-2-yl)methoxy)ethyl)nitrous amide",
    "cas": null,
    "active": "독실아민(Doxylamine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 24,
    "name": "N-nitroso-N-desmethyl-doxycycline",
    "iupac": "(4S,4aR,5S,5aR,6R,12aR)-1,5,10,11,12a-pentahydroxy-6-methyl-4-[methyl(nitroso)amino]-3,12-dioxo-4a,5,5a,6-tetrahydro-4H-tetracene-2-carboxamide",
    "cas": null,
    "active": "독시사이클린(Doxycycline)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 23,
    "name": "N-nitroso-nordoxepin",
    "iupac": "N-[(3E or 3Z)-3-(6H-benzo[c][1]benzoxepin-11-ylidene)propyl]-N-methylnitrous amide",
    "cas": null,
    "active": "독세핀(Doxepin)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 22,
    "name": "N-nitroso-dorzolamide",
    "iupac": "(4S, 6S)-4-(ethyl(nitroso)amino)-6-methyl-5, 6-dihydro-4H-thieno[2, 3-b]thiopyran-2-sulfonamide 7, 7-dioxide",
    "cas": null,
    "active": "도르졸라미드(Dorzolamide)",
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 21,
    "name": "N-nitroso-N-desmethyl-dextromethorphan",
    "iupac": "(4bS,8aS,9S)-3-methoxy-11-nitroso-6,7,8,8a,9,10-hexahydro-5H-9,4b-(epiminoethano)phenanthrene",
    "cas": null,
    "active": "덱스트로메토르판(Dextromethorphan)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 20,
    "name": "N-nitroso-N-desmethyl-desvenlafaxine",
    "iupac": "N-(2-(1-Hydroxycyclohexyl)-2-(4-hydroxyphenyl)ethyl)-N-methylnitrous amide",
    "cas": null,
    "active": "데스벤라팍신(Desvenlafaxine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 19,
    "name": "N-nitroso-desloratadine",
    "iupac": "13-chloro-2-(1-nitrosopiperidin-4-ylidene)-4-azatricyclo [9.4.0.03,8]pentadeca-1(11),3(8),4,6,12,14-hexaene",
    "cas": "1246819-22-6",
    "active": "데스로라타딘(Desloratadine)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 18,
    "name": "N-nitroso-dabigatran etexilate",
    "iupac": "Ethyl3-(2-(((4-(N-((hexyloxy)carbonyl)carbamimidoyl)phenyl)(nitroso)amino)methyl)-1-methyl-N-(pyridin-2-yl)-1H-benzo[d]imidazole-5-carboxamido)propanoate",
    "cas": null,
    "active": "다비가트란(Dabigatran)",
    "category": null,
    "ai": "1500",
    "remark": "AMES 음성",
    "date": "2024-06-21",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 17,
    "name": "N-nitroso-N-desmethyl-nintedanib",
    "iupac": "Methyl (Z)-3-(((4-(N-methyl-2-(4-nitrosopiperazin-1-yl)acetamido)phenyl)amino)(phenyl)methylene)-2-oxoindoline-6-carboxylate",
    "cas": null,
    "active": "닌테다닙(Nintedanib)",
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-03-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 16,
    "name": "N-nitroso-nortriptyline (NNORT)",
    "iupac": "N-methyl-N-[3-(2-tricyclo[9.4.0.0^3,8] pentadeca-1(15),3,5,7,11,13-hexaenylidene)propyl]nitrous amide",
    "cas": "55855-42-0",
    "active": "노르트립틸린(Nortriptyline), 아미트립틸린(Amitriptyline)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2024-11-06",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 15,
    "name": "N-nitroso-nebivolol (NNEB)",
    "iupac": "N,N-bis[2-(6-fluoro-3,4-dihydro-2H-chromen-2-yl)-2-hydroxyethyl]nitrous amide",
    "cas": "1391051-68-5",
    "active": "네비보롤(Nebivolol)",
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 14,
    "name": "2-nitroso-octahydrocyclopenta(c)pyrrole",
    "iupac": "2-nitroso-3,3a,4,5,6,6a-hexahydro-1H-cyclopenta[c]pyrrole",
    "cas": "54786-86-6",
    "active": "글리클라지드(Gliclazide)",
    "category": null,
    "ai": "1700",
    "remark": "SAR/read-across, 참조물질 NPYR",
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 13,
    "name": "N-nitroso-desmethyl-galantamine",
    "iupac": "(4aS,6R,8aS)-3-methoxy-11-nitroso-4a,5,9,10,11,12-hexahydro-6H-benzo[2,3]benzofuro[4,3-cd]azepin-6-ol",
    "cas": null,
    "active": "갈란타민(Galantamine)",
    "category": 1,
    "ai": "26.5",
    "remark": null,
    "date": "2025-06-12",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 12,
    "name": "N-nitroso-N-methylaniline (NMPA)",
    "iupac": "N-methyl-N-phenylnitrous amide",
    "cas": "614-00-6",
    "active": null,
    "category": 2,
    "ai": "100",
    "remark": null,
    "date": "2025-02-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 11,
    "name": "1-methyl-4-nitrosopiperazine (MeNP)",
    "iupac": "1-methyl-4-nitrosopiperazine",
    "cas": "16339-07-4",
    "active": null,
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2025-01-09",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 10,
    "name": "N-nitroso-N-methyl-4-aminobutyric acid (NMBA)",
    "iupac": "4-[methyl(nitroso)amino]butanoic acid",
    "cas": "61445-55-4",
    "active": null,
    "category": 4,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 9,
    "name": "N-nitroso-ethylisopropylamine (NEIPA)",
    "iupac": "N-ethyl-N-propan-2-ylnitrous amide",
    "cas": "16339-04-1",
    "active": null,
    "category": 3,
    "ai": "400",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 8,
    "name": "N-nitroso-diisopropylamine (NDIPA)",
    "iupac": "N,N-di(propan-2-yl)nitrous amide",
    "cas": "601-77-4",
    "active": null,
    "category": 5,
    "ai": "1500",
    "remark": null,
    "date": "2024-12-04",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 7,
    "name": "N-nitroso-pyrrolidine (NPYR)",
    "iupac": "1-nitrosopyrrolidine",
    "cas": "930-55-2",
    "active": null,
    "category": null,
    "ai": "1700",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 6,
    "name": "N-nitroso-piperidine (NPIP)",
    "iupac": "1-nitrosopiperidine",
    "cas": "100-75-4",
    "active": null,
    "category": null,
    "ai": "1300",
    "remark": null,
    "date": "2023-12-13",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 5,
    "name": "N-nitroso-morpholine (NMOR)",
    "iupac": "4-nitrosomorpholine",
    "cas": "59-89-2",
    "active": null,
    "category": null,
    "ai": "127",
    "remark": null,
    "date": "2022-02-17",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 4,
    "name": "N-nitroso-dipropylamine (NDPA)",
    "iupac": "N,N-dipropylnitrous amide",
    "cas": "621-64-7",
    "active": null,
    "category": null,
    "ai": "26.5",
    "remark": "SAR/read-across, 참조물질 NDEA",
    "date": "2021-11-18",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 3,
    "name": "N-nitroso-di-n-butylamine (NDBA)",
    "iupac": "N,N-dibutylnitrous amide",
    "cas": "924-16-3",
    "active": null,
    "category": null,
    "ai": "26.5",
    "remark": "SAR/read-across, 참조물질 NDEA",
    "date": "2021-11-09",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 2,
    "name": "N-nitroso-diethylamine (NDEA)",
    "iupac": "N,N-diethylnitrous amide",
    "cas": "55-18-5",
    "active": null,
    "category": null,
    "ai": "26.5",
    "remark": null,
    "date": "2018-11-20",
    "publishDate": "2026년 8월 공고"
  },
  {
    "no": 1,
    "name": "N-nitroso-dimethylamine (NDMA)",
    "iupac": "N,N-dimethylnitrous amide",
    "cas": "62-75-9",
    "active": null,
    "category": null,
    "ai": "96",
    "remark": null,
    "date": "2018-08-06",
    "publishDate": "2026년 8월 공고"
  }
];
